# Generated by Django 4.1.7 on 2023-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        
    ]
