# Generated by Django 4.1.7 on 2023-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='decision',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
