# Generated by Django 4.1.7 on 2023-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_demande_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='decision',
            field=models.CharField(default='NotYet', max_length=50, null=True),
        ),
    ]
