# Generated by Django 4.1.7 on 2023-04-21 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_add_created_to_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='affected',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
