# Generated by Django 4.1.7 on 2023-04-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_add_prediction_to_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='AgentId',
            field=models.IntegerField(null=True),
        ),
    ]
