# Generated by Django 4.1.7 on 2023-04-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_demande_decision'),
        ('credit', '0005_alter_demande_clientid'),
    ]

    operations = [
    ]
