# Generated by Django 4.1.7 on 2023-05-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_demande_agentmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='agent_associé',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
