# Generated by Django 4.1.7 on 2023-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_merge_20230401_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='decision',
            field=models.CharField(default='notyet', max_length=50),
        ),
    ]
