# Generated by Django 4.1.7 on 2023-04-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_demande_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='verified',
        ),
    ]
