# Generated by Django 4.1.7 on 2023-03-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
