# Generated by Django 4.1.7 on 2023-04-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_email_alter_useraccount_name'),
        ('user', '0003_alter_useraccount_is_banquier'),
    ]

    operations = [
    ]
