# Generated by Django 4.1.7 on 2023-04-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20230401_2319'),
        ('user', '0004_merge_20230405_1545'),
    ]

    operations = [
    ]
