# Generated by Django 4.1.7 on 2023-04-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20230411_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_banquier',
            field=models.BooleanField(default=False),
        ),
    ]
