# Generated by Django 4.1.7 on 2023-04-21 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useraccount_is_banquier'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
