# Generated by Django 4.1.7 on 2023-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_inscription_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
