# Generated by Django 4.1.7 on 2023-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_image_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image4',
            field=models.TextField(null=True),
        ),
    ]
