# Generated by Django 4.1.7 on 2023-04-23 12:53

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_add_image_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to),
        ),
    ]
