# Generated by Django 4.1.7 on 2023-04-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_nb_mail_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nb_mail',
            field=models.IntegerField(default=0),
        ),
    ]
