# Generated by Django 4.1.7 on 2023-05-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_useraccount_image4'),
        ('user', '0011_alter_nb_mail_user'),
    ]

    operations = [
    ]
